config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :rentals do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:show, :index]

  get "about", to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :rental
  # enum status: ["Pending", "Accepted", "Declined"]
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :bookings, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description_and_address,
  against: [ :title, :description, :address ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rentals
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def create
    @rental = Rental.find(params[:rental_id])
    @booking = Booking.new(booking_params)
    @booking.total_price = @rental.price_per_day * (@booking.end_date - @booking.start_date).to_i
    @booking.rental = @rental
    @booking.user = current_user
    @booking.status = "Pending"
    if @booking.save
      redirect_to bookings_path
    else
      render "rentals/show"
    end
  end

  def show
    @rental = @booking.rental
    @owner = @rental.user
  end

  def index
    @bookings = Booking.where(user: current_user)
    @owner_bookings = Booking.where(rental: Rental.where(user: current_user))
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def accept
    @booking.status = "Accepted"
    @booking.save
    redirect_to booking_path(@booking)
  end

  def decline
    @booking.status = "Declined"
    @booking.save
    redirect_to booking_path(@booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @rentals = Rental.where(address: "Canggu")
  end

  def about
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_rental, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @rentals = Rental.search_by_title_and_description_and_address(params[:query])
    else
      @rentals = Rental.all
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    if @rental.save
      flash[:success] = "Rental was successfully created."
      redirect_to rental_path(@rental)
    else
      flash[:error] = "There was an error saving the rental."
      render :new
    end
  end

  def edit
  end

  def update
    if @rental.update(rental_params)
      redirect_to rental_path(@rental)
    else
      render :edit
    end
  end

  private

  def rental_params
    params.require(:rental).permit(:title, :description, :address, :price_per_day, :rating, :user_id, :headline, photos: [])
  end

  def set_rental
    @rental = Rental.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
        <%= simple_form_for [@rental, @booking], data: { controller: 'flatpickr' } do |f| %>
          <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
          <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" }, id: 'end_time' } %>
          <%= f.button :submit, 'Book Now', class: 'btn btn-primary my-3 w-100' %>
        <% end %>

app/views/bookings/index.html.erb
<div class="container flex">
  <h1>My Bookings</h1>
<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="bookings-tab" data-bs-toggle="tab" data-bs-target="#bookings" type="button" role="tab" aria-controls="bookings" aria-selected="true">Bookings</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="requests-tab" data-bs-toggle="tab" data-bs-target="#requests" type="button" role="tab" aria-controls="requests" aria-selected="false">Requests</button>
  </li>
</ul>



<!-- Tab panes -->

<div class="container justify-content-center mt-4 tab-content">
  <div class="tab-pane active" id="bookings" role="tabpanel" aria-labelledby="bookings-tab">

    <% @bookings.each do |booking| %>
      <div class="card-product mb-2 w-50">
        <% if booking.rental.photos.attached? %>
          <%= cl_image_tag booking.rental.photos.first.key, width: 300, height: 200, crop: :fill %>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/dncij7vr6/image/upload/v1677666474/Rectangle_7_ivn4vk.jpg", class: "card-img-top" %>
        <% end %>
        <div class="card-product-infos flex-grow-1 text-decoration-none">
          <h2 class="text-decoration-none"><%= booking.rental.title %></h2>
          <p class="text-decoration-none">
            From: <%= booking.start_date %>
            <br>
            To: <%= booking.end_date %>
          </p>
          <p class="text-decoration-none">
            Total Price: <strong>$</strong><%= booking.total_price %>
          </p>
          <% if booking.status == "Accepted" %>
          <span class="badge text-bg-success">Success</span>
          <% elsif booking.status == "Pending" %>
          <span class="badge text-bg-warning">Pending</span>
          <% else %>
          <span class="badge text-bg-danger">Declined</span>
          <% end %>
        </div>
        <div class="d-flex flex-column p-4">
          <%= link_to "Change", "#" %>
          <%= link_to "Cancel", "#" %>
        </div>
      </div>
    <% end %>
  </div>






  <div class="tab-pane" id="requests" role="tabpanel" aria-labelledby="requests-tab">
    <div class="container justify-content-center mt-4">
      <% @owner_bookings.each do |booking| %>
        <div class="card-product mb-2 w-50">
          <% if booking.rental.photos.attached? %>
            <%= cl_image_tag booking.rental.photos.first.key, width: 300, height: 200, crop: :fill %>
            <% else %>
            <%= image_tag "https://res.cloudinary.com/dncij7vr6/image/upload/v1677666474/Rectangle_7_ivn4vk.jpg", class: "card-img-top" %>
          <% end %>
          <div class="card-product-infos flex-grow-1">
            <h2><%= booking.rental.title %></h2>
            <p>
              From: <%= booking.start_date %>
              <br>
              To: <%= booking.end_date %>
            </p>
            <p>
              Total Price: <strong>$</strong><%= booking.total_price %>
            </p>
            <% if booking.status == "Accepted" %>
            <span class="badge text-bg-success">Success</span>
            <% elsif booking.status == "Pending" %>
            <span class="badge text-bg-warning">Pending</span>
            <% else %>
            <span class="badge text-bg-danger">Declined</span>
            <% end %>
          </div>
          <div class="d-flex flex-column p-4">
            <%= link_to "Accept", "#" %>
            <%= link_to "Decline", "#" %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container border-light">
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 you successfully booked!</span>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>
  <div class="row">
    <div class="col-12">
      <h1>Booking #<%= @booking.id %></h1>
      <h3><%= @booking.rental.title %></h3>
      <%= cl_image_tag @booking.rental.photos.first.key, height: 300, width: 400, crop: :fill %>
      <p>Start Date: <%= @booking.start_date %></p>
      <p>End Date: <%= @booking.end_date %></p>
      <p>Total Price: <strong>$</strong><%= @booking.total_price %></p>
      <p>Status: <%= @booking.status %></p>
      <p>Client: <%= @booking.user.email %></p>
      <p>Rental: <%= @booking.rental.title %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZenRentals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner my-7" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path("AdobeStock_208033690_atpb2a") %>);">
  <div class="container align-items-center">
    <h1>Pause.</h1>
    <h1>Relax.</h1>
    <h1>Perform.</h1>
    <p>Rent rejuvinating zen equipment for your office or event.</p>
    <%= link_to "Rent Zen", rentals_path, class: "btn btn-primary btn-large font-light  " %>
    <%= link_to "Story", about_path, class: "btn btn-large btn-custom-transparent font-light" %>
  </div>
</div>
<h3 class="mt-5 mb-4" style="text-align: center">Browse zen categories</h3>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.incimages.com/uploaded_files/image/1920x1080/energypod_65247.jpg)">
        Nap Pods & Massage Chairs
      </div>
    </div>
    <div class="col">
      <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://integrisok.com/-/media/Blog/19-Jan-Feb/Woman-in-a-cryochamber.ashx?as=1&mh=405&mw=720&revision=aa19cf45-5660-4dac-88ae-2575fc834fae&hash=CCFAD2680849A2574124941231869D8E)">
        Saunas, Steambaths & Cryochambers
      </div>
    </div>
    <div class="col">
      <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://cdn.home-designing.com/wp-content/uploads/2013/03/Office-interior-vertical-garden.jpeg)">
        Vertical Gardens & Water Features
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.urban-office.com/images/headers/acoustic-pods.jpg)">
        Silent Office Booths
      </div>
    </div>
    <div class="col">
      <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path("booth_w8qzxc") %>);">
        Tiny Cabins & Outdoor Offices
      </div>
    </div>
    <div class="col">
      <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path("experiences_gm9ez3") %>);">
        Custom Multisensory Experiences
      </div>
    </div>
  </div>
</div>


<h3 class="mt-5" style="text-align: center;">Unique experiences</h3>
<p style="text-align: center">Surprise employees or conference goers with mesmerizing, unique zen experiences enabled through state-of-the art technology</p>


<div class="container my-4">
  <div class="banner banner-unique-experiences my-7 d-flex align-items-center justify-content-center mx-auto" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path("teamlab_jzqhuw") %>);">
    <%= link_to "Enter a new vision of zen", rentals_path, class: "btn btn-large btn-custom-transparent-secondary" %>
  </div>
</div>

<h3 class="mt-5" style="text-align: center;">Discover zen equipment in <span style="color: #B91372;">Canggu</span></h1>
<div class="container">
  <div class="cards-container">
    <% @rentals.each do |rental| %>
    <%= link_to rental_path(rental) do %>
      <div class="main-card text-decoration-none">
      <% if rental.photos.attached? %>
        <%= cl_image_tag rental.photos.first.key, width: 300, height: 200, crop: :fill %>
        <% else %>
        <%= image_tag "https://res.cloudinary.com/dncij7vr6/image/upload/v1677666474/Rectangle_7_ivn4vk.jpg", class: "card-img-top" %>
      <% end %>
        <div class="content-container mt-3 px-3">
          <h3>
            <%= rental.title %>
          </h3>
          <p>
            <%= rental.headline %>
          </p>
          <div class="detail-box">
            <div class="text-decoration-none">
              <strong>$</strong></strong><%= rental.price_per_day %>
            </div>
            <div class="text-decoration-none">
              <%= rental.address %>
            </div>
            <div class="text-decoration-none">
              <i class="fa-solid fa-star"></i>
              <%= rental.rating %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>
  

app/views/rentals/index.html.erb
<div class="container">
  <div class="cards-container">
    <% @rentals.each do |rental| %>
    <%= link_to rental_path(rental) do %>
      <div class="main-card text-decoration-none">
      <% if rental.photos.attached? %>
        <%= cl_image_tag rental.photos.first.key, width: 300, height: 200, crop: :fill %>
        <% else %>
        <%= image_tag "https://res.cloudinary.com/dncij7vr6/image/upload/v1677666474/Rectangle_7_ivn4vk.jpg", class: "card-img-top" %>
      <% end %>
        <div class="content-container mt-3 px-3">
          <h3>
            <%= rental.title %>
          </h3>
          <p>
            <%= rental.headline %>
          </p>
          <div class="detail-box">
            <div class="text-decoration-none">
              <strong>$</strong></strong><%= rental.price_per_day %>
            </div>
            <div class="text-decoration-none">
              <%= rental.address %>
            </div>
            <div class="text-decoration-none">
              <i class="fa-solid fa-star"></i>
              <%= rental.rating %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rentals/new.html.erb
<div class="container">
  <h1>List your zen equipment</h1>
  <%= simple_form_for @rental do |f| %>
    <%= f.input :title %>
    <%= f.input :headline %>
    <%= f.input :description %>
    <%= f.input :price_per_day %>
    <%= f.input :address %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, "List your zen equipment" %>
  <% end %>

</div>

app/views/rentals/show.html.erb
<div class="container pt-2">
  <div class="row">
      <div class="col-md-6">
        <% if @rental.photos.attached? %>
          <%= cl_image_tag @rental.photos.first.key, crop: :thumb, width: 600, height: 400, class: "w-100 h-100" %>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/dncij7vr6/image/upload/v1677666474/Rectangle_7_ivn4vk.jpg", class: "card-img-top" %>
        <% end %>
      </div>
      <div class="col-md-6">
        <div class="row">
          <% if @rental.photos.attached? %>
            <% @rental.photos[1..4].each do |photo| %>
              <div class="col-sm-6">
                <div class="my-2 secondary-images" style="position: relative; overflow: hidden;">
                  <%= cl_image_tag photo.key, crop: :thumb, style: "object-fit: cover; object-position: center;" %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>


  <div class="row">
    <div class="col-8">
      <div class="rental-title border-bottom my-4">
        <h1><%= @rental.title %></h1>
      </div>
      <div class="icon-bar border-bottom my-4 d-flex">
        <div class="d-flex flex-column align-items-center">
          <i class="fa-solid fa-bed"></i>
          <p>Sleep-Enhancing</p>
        </div>

        <div class="d-flex mx-5 flex-column align-items-center">
          <i class="fa-solid fa-brain"></i>
          <p>Brain-Boosting</p>
        </div>

        <div class="d-flex flex-column align-items-center">
          <i class="fa-solid fa-truck-fast"></i>
          <p>Instant Delivery</p>
        </div>

      </div>



      <div class="rental-content border-bottom my-4">
        <p> <%= @rental.description %></p>
      </div>
    </div>
    <div class="col-4 mt-4">
      <div class="border p-4">
        <div class="row justify-content-between">
          <div class="col-6">
            <h4> $ <%= @rental.price_per_day %> day</h4>
          </div>
          <div class="col-6 text-end">
            <h4> <%= @rental.rating %> <i class="fa-solid fa-star"></i> </h4>
          </div>
        </div>
        <div class="booking-form">
          <%= render 'bookings/form', rental: @rental %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
       <%= cl_image_tag("Logo_1_qqahw9", width: 400) %>
    <% end %>


    <div class="mx-auto text-center">
      <%= form_tag rentals_path, method: "get", class: "nav-link" do %>
        <%= text_field_tag :query, params[:query], placeholder: "Type location or category...", class: "search-field" %>
        <%= submit_tag "Search", class: "btn" %>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>


          <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Rent Out", new_rental_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
       <%= cl_image_tag("Logo_1_qqahw9", width: 400) %>
    <% end %>


    <div class="mx-auto text-center">
      <%= form_tag rentals_path, method: "get", class: "nav-link" do %>
        <%= text_field_tag :query, params[:query], placeholder: "Type location or category...", class: "search-field" %>
        <%= submit_tag "Search", class: "btn" %>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>


          <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Rent Out", new_rental_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>